accounts:
  - name: alice
    coins: ["20000uccc", "200000000ucommercio"]
  - name: bob
    coins: ["10000uccc", "100000000ucommercio"]
validator:
  name: alice
  staked: "100000000ucommercio"
client:
  vuex:
    path: "vue/src/store"
  openapi:
    path: "docs_3_0/static/openapi.yml"
faucet:
  name: bob
  coins: ["5uccc", "100000ucommercio"]
genesis:
  app_state:
    government:
      governmentAddress: "did:com:1m4l9su8ef0pdy9dhp2jl0j9yq7knu0ztu7qmr0"
    vbr:
      poolAmount:
        -
          denom: "ucommercio"
          amount: "10000000.000000000000000000"
      rewardRate: "0.010000000000000000"
    staking:
      params:
        bond_denom: "ucommercio"